openapi: "3.0.0"
info:
  version: 0.0.1
  title: Scrum Poker
paths:
  /table/{tableId}/user:
    post:
      summary: Add new user to table
      operationId: addUser
      tags:
        - table
      parameters:
        - name: tableId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: New user registration data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserRequest'
      responses:
        '200':
          description: New user added to table properly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '500':
          description: User cant be registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /table:
    get:
      summary: List all tables
      operationId: allTables
      tags:
        - table
      responses:
        '200':
          description: All available tables
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TableDto'
    post:
      summary: Add new table
      operationId: addTable
      tags:
        - table
      requestBody:
        description: Parameters required to create new table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTableRequest'
      responses:
        '200':
          description: Table added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableDto'
        '500':
          description: Table cant be created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nick:
          type: string
        role:
          type: string

    AddUserRequest:
      type: object
      properties:
        nick:
          type: string
        role:
          type: string

    TableDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    AddTableRequest:
      type: object
      properties:
        name:
          type: string

